server:
  port: 8858

spring:
  application:
    name: cheetah-messages-service
  datasource:
    url: jdbc:mysql://81.68.177.58:8080/cheetah_messages?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    #root: DEBUG
    com.alibaba.nacos.client.config.impl: WARN

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://81.68.177.58:8848
  provider:
    timeout: 30000
    check: false
  consumer:
    timeout: 30000
    check: false


nacos:
  config:
    server-addr: 81.68.177.58:8848
    type: yaml
    data-id: cheetah-messages-service.yml
    auto-refresh: true
    group: DEFAULT_GROUP
    bootstrap:
      enable: true
      log:
        enable: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




