server:
  port: 8878

spring:
  application:
    name: cheetah-messages-handler

logging:
  level:
    #root: DEBUG
    com.alibaba.nacos.client.config.impl: WARN

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://81.68.177.58:8848

nacos:
  config:
    server-addr: 81.68.177.58:8848
    type: yaml
    data-id: cheetah-messages-handler.yml
    auto-refresh: true
    group: DEFAULT_GROUP
    bootstrap:
      enable: true
      log-enable: true

messages:
  account:
    server-addr: 81.68.177.58:8848
    data-id: local.properties
    group: DEFAULT_GROUP
    bootstrap:
      enable: true


