server:
  port: 8868

spring:
  application:
    name: cheetah-messages-mq

logging:
  level:
    #root: DEBUG
    com.alibaba.nacos.client.config.impl: WARN

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://81.68.177.58:8848

cheetah:
  business:
    topic:
      name: send.messages.direct           # 发送消息的交换机名字
    recall:
      topic:
        name: recall.messages.direct       # 撤回消息的交换机名字
    rabbitmq:
      address: 81.68.177.58:15672
      username: guest
      password: guest
  mq:
    pipeline: rabbitMq

nacos:
  config:
    server-addr: 81.68.177.58:8848
    type: yaml
    data-id: cheetah-messages-mq.yml
    auto-refresh: true
    group: DEFAULT_GROUP
    bootstrap:
      enable: true
      log:
        enable: true

